### PR TITLE
Store Submission in Dedicated Table

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to store submission data in dedicated table.

It is now WIP, this PR is for progress update.

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Simple ODK form for testing:
[xlsform_template.xlsx](https://github.com/stats4sd/tape-data-system/files/15234312/xlsform_template.xlsx)

**Comment by dan-tang-ssd** [comment]
This PR is now ready for review.

It contains below changes when retrieving ODK submission:
  - check if dataset mapped to xlsform template section
  - check if database table defined for a dataset
  - check if database table exist
  - get table columns of a database table
  - only grab entity values that existed in table columns (to avoid non exist columns appear in INSERT statement)
  - store grabbed entity values as a new record
  - in master table and detail table, use column "odk_id" to link master records and detail records
  - we can support repeat group in level 1 now, we cannot support nested repeat group yet

**Comment by dan-tang-ssd** [comment]
Here is the ODK form with repeat group for testing:
[odk-example-with-repeat.xlsx](https://github.com/stats4sd/tape-data-system/files/15291889/odk-example-with-repeat.xlsx)

**Review by dave-mills — COMMENTED** [review]
First comment, before I go into the submodule package updates: 

I know this is just a test/demo case, but I think it would be a better test/demo if we considered what `DrinksFormMain` and `DrinksFormDrinkRepeat` actually are in the context of the ODK survey you've used. I don't think this requires much, but for example: 

- What do these 2 models actually represent? I think they represent a survey response (which could be linked to a `survey respondent` entry in a real survey), and "drink selected" (Maybe called something like `DrinkInfo`.
- When you think about it in this way, you hopefully immediately see that you need a relationship between the SurveyResponse (`DrinksFormMain`) and DrinkInfo (`DrinksFormMain`) - this is important, because in most real scenarios, the repeat-group data Model would belong to the parent model, and the parent model (the "main survey") would have many repeat group models linked to it. 

This probably has some implications for how these models are populated!

**Review by dave-mills — DISMISSED** [review]
I like the approach of comparing the Model table's columns with the ODK Schema to make sure we're getting all required variables and not trying to add variables that don't exist in the database. Very neat. I tested it with the real TAPE survey (just by adding a few key variables to the drinks_form_main table and linking that dataset to the main part of the form), and it worked nicely. 

3 comments:

1. What does the `odk_id` represent in the linked data models? It looks like a link to the ODK submission - in which case I think it would be better represented by a relationship - of course, the issue with this is that we cannot add the inverse relationship to the package Submisison class; which means we would need to ask the devs to extend their own Submission model to add those relationships. Not ideal! But something to consider. 

If we don't use a relationship here, we should at least have a helper function to let devs quickly get the linked submission from a Model, e.g. `$drinksFormMain->getSubmission()`, which returns the submission model. 

3. I think the OdkLInkService->processEntryFromSection() updates is a good opportunity for refactoring. The logic seems good here, but I think it would be good to extract the different actions into their own functions - e.g. separate out the creation of the Entity and EntityValues from the creation of the linked data Model. 

3. I would like to highlight the variables that do *not* exist on the Model but do exist on the form. For example, in the demo drinks form, there are `start_date`, `coffee`, `coffee_number` and `drinks` variables that are not stored in the database table. This is a great test example, because here it makes sense that the `drinks` variable is not stored (as that information should really be at the DrinkFormDrinkRepeat level), but it might be that the developer or user has accidentally missed out `coffee` and `coffee_number`. I wonder if there is a way to highlight these variables somewhere. 

I don't think these comments need to be addressed explicitly here. Given this works, I suggest merging this into the dev branch so we can have it available for the Ethiopia work, and then we can address the above in separate PRs.

**Comment by dan-tang-ssd** [comment]
> First comment, before I go into the submodule package updates:
> 
> I know this is just a test/demo case, but I think it would be a better test/demo if we considered what `DrinksFormMain` and `DrinksFormDrinkRepeat` actually are in the context of the ODK survey you've used. I don't think this requires much, but for example:
> 
>     * What do these 2 models actually represent? I think they represent a survey response (which could be linked to a `survey respondent` entry in a real survey), and "drink selected" (Maybe called something like `DrinkInfo`.
> 
>     * When you think about it in this way, you hopefully immediately see that you need a relationship between the SurveyResponse (`DrinksFormMain`) and DrinkInfo (`DrinksFormMain`) - this is important, because in most real scenarios, the repeat-group data Model would belong to the parent model, and the parent model (the "main survey") would have many repeat group models linked to it.
> 
> 
> This probably has some implications for how these models are populated!

Thank you Dave for your comments.

Yes, Drinks ODK form is for test or demonstration purpose.

The table names and model names are named to show the root item and repeat group concepts in an obvious way:
 - root item: drink_form_main, DrinksFormMain
 - repeat group: drink_form_drink_repeat, DrinksFormDrinkRepeat

Column "odk_id" is added in master table (for root item) and detail table (for repeat group). So that we have a column to find all records belong to a single submission in the extraction file.

I use "odk_id" as column name because it is generic. We need a simple and generic column name in filement-odk-link package. I want to avoid adding complicated code in OdkLinkService. (e.g. getting relationship name of a model class on the fly...)
We can add relationship in model class to make it more useful.

It would be better if we can use Tape ODK form instead of Drinks ODK form.
I tried to fill in Tape ODK form submitted via staging env in ODK Collect, I cannot further proceed when choosing a farm as it cannot read the CSV file... error occurred...

**Comment by dan-tang-ssd** [comment]
>     1. What does the `odk_id` represent in the linked data models? It looks like a link to the ODK submission - in which case I think it would be better represented by a relationship - of course, the issue with this is that we cannot add the inverse relationship to the package Submisison class; which means we would need to ask the devs to extend their own Submission model to add those relationships. Not ideal! But something to consider.

Column "odk_id" is added in master table and detail table, it allows to link all related records of a single submission.
I added it just after realising there is nothing to link master record and detail record in the extraction file. We need a generic column name in a package. 


> If we don't use a relationship here, we should at least have a helper function to let devs quickly get the linked submission from a Model, e.g. `$drinksFormMain->getSubmission()`, which returns the submission model.

Yes, we can add relationships in model classes.


>     3. I think the OdkLInkService->processEntryFromSection() updates is a good opportunity for refactoring. The logic seems good here, but I think it would be good to extract the different actions into their own functions - e.g. separate out the creation of the Entity and EntityValues from the creation of the linked data Model.

Yes, I fully agree. It is a good time to refactor OdkLInkService->processEntryFromSection() before it becomes too complicated.


>     4. I would like to highlight the variables that do _not_ exist on the Model but do exist on the form. For example, in the demo drinks form, there are `start_date`, `coffee`, `coffee_number` and `drinks` variables that are not stored in the database table. This is a great test example, because here it makes sense that the `drinks` variable is not stored (as that information should really be at the DrinkFormDrinkRepeat level), but it might be that the developer or user has accidentally missed out `coffee` and `coffee_number`. I wonder if there is a way to highlight these variables somewhere.

Yes, it is intended not to add these columns. The purpose is to show that the program will not crash even there are columns existed in submission data but not existed in database table. The developer should notice there are missing columns during internal testing.


> I don't think these comments need to be addressed explicitly here. Given this works, I suggest merging this into the dev branch so we can have it available for the Ethiopia work, and then we can address the above in separate PRs.

Yes, let's work on these issues in separate PRs.

**Comment by dave-mills** [comment]
> Column "odk_id" is added in master table and detail table, it allows to link all related records of a single submission.
I added it just after realising there is nothing to link master record and detail record in the extraction file. We need a generic column name in a package.

I don't think we need to make it that generic though - we know it's a link to submissions, so perhaps we can use `submission_Id` so it's linked to the Submission model's primary key, instead of the `odk_id` variable. (yes, the `odk_id` should be unique, but I don't think the `odk_id` on the Submission table is overly useful; and I honestly think it's mostly there for us while we build this system. 

Using the submissions.id also makes it super easy to add a quick `submission(): belongsTo` relationship method onto the data models. Perhaps that can be included in a `IsUpdatedViaOdkForm` trait that devs can add to their custom data models like `DrinksFormMain` (not sure about that trait  name, but hopefully you get the idea)

**Review by dave-mills — APPROVED** [review]
I guess these are after merging in the changes from the dev branch. Looks good to me 👍

**Pull request merged**
