### PR TITLE
Fixes typo in main survey table

### PR DESCRIPTION
**Pull request by dave-mills**

### CODE REVIEW

**Comment by dave-mills** [comment]
!Ah, hang on - need to remove the package changes...

EDIT: That's better. Only 1 file changed.

**Comment by dan-tang-ssd** [comment]
Um... do we also need to change it from decimal(8,2) to decimal(20,2)?

**Comment by dave-mills** [comment]
Probably not (caet scores are max 100 with 2 decimals), but I will for consistency.

**Comment by dan-tang-ssd** [comment]
It works well, I think it is good to merge now.

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
