### PR TITLE
fix model refs in odk env

### PR DESCRIPTION
**Pull request by dave-mills**

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I did below items:
1. checkout this branch
2. .env file, add new config items
3. run "php artisan migrate:fresh --seed"

It throws cURL error for TestSeeder.php...

image

**Comment by dave-mills** [comment]
Ciara and I just solved a problem where if you don't have the ODK Central link setup in .env, it still tries to connect. I pushed a fix to the filament-odk-link package's `datasets-with-models` branch. I assume this is that issue. Can you try with the latest version of this branch and double check the package is updated? 

Cheers :)

**Comment by dan-tang-ssd** [comment]
I pulled latest code from correct branch for main repo and submodule:

image

image

---

Then I run "php artisan migrate:fresh --seed", it throws cURL error when running PlatformSeeder.php
Please find my .env config items in below screen shot, is there anything I missed?

image

**Comment by dave-mills** [comment]
Ahhah, so the difference is that I didn't have the ODK_ENDPOINT at all in my .env file. If you look in the filament-odk-link config  file, you'll see: 

```
 'base_endpoint' => env('ODK_ENDPOINT', env('ODK_URL') . '/v1'),
```

This means that if the ODK_ENDPOINT env variable is present, that will be used. Otherwise it'll default to the ODK_URL with `/v1` appended. 

This discussion tells me that we should entirely remove the ODK_ENDPOINT env variable from the .env.example, remove the reference to it in the config file, and just always use that 'default' entry for the base_endpoint. That will avoid confusion for future setups. I've just done that in the package and this branch.

**Comment by dan-tang-ssd** [comment]
Good news. I can successfully run all migrations and seeder files now.

I will proceed to add a ODK form to a team and update.

Thank you Dave and Ciara.

image

**Comment by dave-mills** [comment]
Great! I'll merge this branch into dev.

**Pull request merged**
